### ISSUE TITLE
`numpy` and `polygon` are not compatible

### ISSUE THREAD

**Issue by Coobiw** [ViTAE-Transformer/DeepSolo#30]
Hello, thanks for the great job! When I setup the env, I find that:
```
>>> from Polygon.cPolygon import *
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qbw/anaconda3/envs/deepsolo/lib/python3.8/site-packages/Polygon/__init__.py", line 5, in <module>
    from Polygon.cPolygon import *
ImportError: numpy.core.multiarray failed to import
```

This error ruined my eval when pretrain. How can I fix it up? Thanks for your answer sincerely.

**Comment by Coobiw** [comment]
Amazing, I re-install the whole venv and find that `pip install numpy --upgrade` works. I have tried to do this but couldn't work ever. Now, it works. Sorry for my interrupt!
