### ISSUE TITLE
Cannot implement DeepSolo on local environment or on Kaggle or any other cloud 

### ISSUE THREAD

**Issue by kunalpurkayastha** [ViTAE-Transformer/DeepSolo#31]
When trying to finetune or pretrain the DeepSolo I'm getting the following error on Kaggle

Traceback (most recent call last):
  File "tools/train_net.py", line 27, in <module>
    from detectron2.data import MetadataCatalog, build_detection_train_loader, build_detection_test_loader
  File "/opt/conda/lib/python3.7/site-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/opt/conda/lib/python3.7/site-packages/detectron2/data/build.py", line 14, in <module>
    from detectron2.structures import BoxMode
  File "/opt/conda/lib/python3.7/site-packages/detectron2/structures/__init__.py", line 6, in <module>
    from .keypoints import Keypoints, heatmaps_to_keypoints
  File "/opt/conda/lib/python3.7/site-packages/detectron2/structures/keypoints.py", line 6, in <module>
    from detectron2.layers import interpolate
  File "/opt/conda/lib/python3.7/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/opt/conda/lib/python3.7/site-packages/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: /opt/conda/lib/python3.7/site-packages/detectron2/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

Also how can I use DeepSolo on my Ubuntu 22.04 (My hardware specs are CPU-Ryzen 7 5600H, GPU- 4GB Nvidia RTX 3050, RAM- 16GB)

Either I face the issue of AdelaiDet or some CUDA error all the time in my local machine

**Comment by ymy-k** [comment]
Maybe detectron2 was not correctly built.

**Comment by kunalpurkayastha** [comment]
> 

I'm using the below version of detectrol2
detectron2==0.1.3

can you please tell me which version of what is required specifically?
as most of the errors I'm facing to implement DeepSolo is due to version mismatch

**Comment by ymy-k** [comment]
Detectron2 v0.6 & torch 1.9 + cuda11.1 were used.
