### ISSUE TITLE
load_zip_file Error loading the ZIP archive

### ISSUE THREAD

**Issue by YuMJie** [ViTAE-Transformer/DeepSolo#52]
When I evaluate the vitae on ic15, some error happened: The det.zip exists on the path
```
[12/22 07:47:44 d2.evaluation.evaluator]: Total inference time: 0:01:48.998131 (0.220198 s / iter per device, on 1 devices)
[12/22 07:47:44 d2.evaluation.evaluator]: Total inference pure compute time: 0:01:47 (0.217200 s / iter per device, on 1 devices)
[12/22 07:47:44 adet.evaluation.text_evaluation_all]: Saving results to /data_local/deepsolo/output/vitaev2_s/150k_tt_mlt_13_15/finetune/totaltext/inference/text_results.json
['text_results.json', 'det.zip', 'det_full.zip']
/data_local/deepsolo/output/vitaev2_s/150k_tt_mlt_13_15/finetune/totaltext/inference/det.zip
Error!
load_zip_file Error loading the ZIP archive

Traceback (most recent call last):
  File "train_net.py", line 304, in <module>
    launch(
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "train_net.py", line 281, in main
    res = Trainer.test(cfg, model) # d2 defaults.py
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 619, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/detectron2/evaluation/evaluator.py", line 213, in inference_on_dataset
    results = evaluator.evaluate()
  File "/data_local/deepsolo/adet/evaluation/text_evaluation_all.py", line 438, in evaluate
    text_result["e2e_method"] = "None-" + text_result["e2e_method"]
KeyError: 'e2e_method'
```

**Comment by jihuan1203** [comment]
我也遇到了同样的错误，想知道你是怎么解决的
