### ISSUE TITLE
how to solve it?

### ISSUE THREAD

**Issue by SSSlump** [ViTAE-Transformer/DeepSolo#56]
Traceback (most recent call last):
  File "tools/train_net.py", line 43, in <module>
    from adet.data.dataset_mapper import DatasetMapperWithBasis
  File "/root/autodl-tmp/DeepSolo-main/adet/__init__.py", line 1, in <module>
    from adet import modeling
  File "/root/autodl-tmp/DeepSolo-main/adet/modeling/__init__.py", line 2, in <module>
    from .text_spotter import TransformerPureDetector
  File "/root/autodl-tmp/DeepSolo-main/adet/modeling/text_spotter.py", line 9, in <module>
    from adet.layers.pos_encoding import PositionalEncoding2D
  File "/root/autodl-tmp/DeepSolo-main/adet/layers/__init__.py", line 1, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/root/autodl-tmp/DeepSolo-main/adet/layers/ms_deform_attn.py", line 17, in <module>
    from adet import _C
ImportError: cannot import name '_C' from partially initialized module 'adet' (most likely due to a circular import) (/root/autodl-tmp/DeepSolo-main/adet/__init__.py)

**Comment by sraimund** [comment]
Maybe you forgot running
```
python setup.py build develop
```
to build the _C module.
